---
title: "Demo"
author: "ponponlin"
date: "May, 20, 2017"
output:
  html_document:
    highlight: haddock
    theme: readable
---

<br/>
<br/>

----------------------------------------------------------------


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
	warning = FALSE
  )
library(dplyr)
library(highcharter)
```

```{r echo=FALSE}
# AM5~9 總流量平均
new.mean.in <- read.csv("mean.in.csv", fileEncoding = "big5") 
# 每個時段平均流量
mean.n.inn <- read.csv("mean.n.csv", fileEncoding = "big5") #進站 
mean.n.out <- read.csv("mean.o.csv", fileEncoding = "big5") #出站

highchart() %>%
  hc_title(text ="平日早上時段進出站") %>%
  hc_xAxis(categories=mean.n.inn$X ,title = list(text = "時間點") ) %>%
  hc_yAxis(title = list(text = "捷運站")) %>%
  hc_add_series(data= mean.n.inn$X6 , name="in6") %>%
  hc_add_series(data= mean.n.inn$X7, name="in7") %>%
  hc_add_series(data= mean.n.inn$X8 , name="in8") %>%
  hc_add_series(data= mean.n.out$X6, name="out6") %>%
  hc_add_series(data= mean.n.out$X7, name="out7") %>%
  hc_add_series(data= mean.n.out$X8, name="out8") 

highchart() %>%
  hc_title(text ="平日晚上時段進出站") %>%
  hc_xAxis(categories=mean.n.inn$X ,title = list(text = "時間點") ) %>%
  hc_yAxis(title = list(text = "捷運站")) %>%
  hc_add_series(data= mean.n.inn$X17 , name="in17") %>%
  hc_add_series(data= mean.n.inn$X18 , name="in18") %>%
  hc_add_series(data= mean.n.inn$X19 , name="in19") %>%
  hc_add_series(data= mean.n.inn$X22, name="in22") %>% 
  hc_add_series(data= mean.n.out$X17, name="out17") %>%
  hc_add_series(data= mean.n.out$X18, name="out18") %>%
  hc_add_series(data= mean.n.out$X19, name="out19")  %>%
  hc_add_series(data= mean.n.out$X22, name="out22") 

highchart() %>%
  hc_title(text ="捷運站分時") %>%
  hc_xAxis(categories= new.mean.in$time) %>%
  hc_add_series(data= new.mean.in$台北車站 , name="北車") %>% 
  hc_add_series(data= new.mean.in$景安 , name="景安") %>%  
  hc_add_series(data= new.mean.in$頂溪 , name="頂溪") %>% 
  hc_add_series(data= new.mean.in$市政府 , name="市政府") %>% 
  hc_add_series(data= new.mean.in$松江南京 , name="松江南京") %>%  
  hc_add_series(data= new.mean.in$公館 , name="公館") %>% 
  hc_add_series(data= new.mean.in$萬芳社區 , name="萬芳社區") %>% 
  hc_add_series(data= new.mean.in$板橋 , name="板橋") %>% 
  hc_add_series(data= new.mean.in$大直 , name="大直") %>% 
  hc_add_series(data= new.mean.in$淡水 , name="淡水") %>% 
  hc_add_series(data= new.mean.in$西門 , name="西門", color="#014c45") 

```

<br/>
<br/>

----------------------------------------------------------------

